import sys

# These settings takes priority
#
# ALLREDUCE:
# ALLREDUCE_BINOMIAL_TREE_MIN
# ALLREDUCE_BINOMIAL_TREE_MAX
# ALLREDUCE_FLAT_TREE_MIN
# ALLREDUCE_FLAT_TREE_MAX
# ALLREDUCE_STATIC_FANOUT_MIN
# ALLREDUCE_STATIC_FANOUT_MAX
#
# REDUCE:
# REDUCE_BINOMIAL_TREE_MIN
# REDUCE_BINOMIAL_TREE_MAX
# REDUCE_FLAT_TREE_MIN
# REDUCE_FLAT_TREE_MAX
# REDUCE_STATIC_FANOUT_MIN
# REDUCE_STATIC_FANOUT_MAX
#
# SCAN:
# SCAN_BINOMIAL_TREE_MIN
# SCAN_BINOMIAL_TREE_MAX
# SCAN_FLAT_TREE_MIN
# SCAN_FLAT_TREE_MAX
# SCAN_STATIC_FANOUT_MIN
# SCAN_STATIC_FANOUT_MAX
#
# SCAN:
# SCAN_BINOMIAL_TREE_MIN
# SCAN_BINOMIAL_TREE_MAX
# SCAN_FLAT_TREE_MIN
# SCAN_FLAT_TREE_MAX
# SCAN_STATIC_FANOUT_MIN
# SCAN_STATIC_FANOUT_MAX
#
# BARRIER:
# BARRIER_BINOMIAL_TREE_MIN
# BARRIER_BINOMIAL_TREE_MAX
# BARRIER_FLAT_TREE_MIN
# BARRIER_FLAT_TREE_MAX
# BARRIER_STATIC_FANOUT_MIN
# BARRIER_STATIC_FANOUT_MAX
#
# BCAST:
# BCAST_BINOMIAL_TREE_MIN
# BCAST_BINOMIAL_TREE_MAX
# BCAST_FLAT_TREE_MIN
# BCAST_FLAT_TREE_MAX
# BCAST_STATIC_FANOUT_MIN
# BCAST_STATIC_FANOUT_MAX
#
# BARRIER:
# BARRIER_BINOMIAL_TREE_MIN
# BARRIER_BINOMIAL_TREE_MAX
# BARRIER_FLAT_TREE_MIN
# BARRIER_FLAT_TREE_MAX
# BARRIER_STATIC_FANOUT_MIN
# BARRIER_STATIC_FANOUT_MAX
#
# And if they are not defined the following
# will be checked
#
# FLAT_TREE_MIN
# FLAT_TREE_MAX
# 
# STATIC_FANOUT_MIN
# STATIC_FANOUT_MAX
#
# BINOMIAL_TREE_MIN
# BINOMIAL_TREE_MAX

COLLECTIVE_FORCE_BINOMIAL_TREE = True

STATIC_TREE_FANOUT_COUNT = 2 

SOCKET_RECEIVE_BYTECOUNT = 4096
SOCKET_POOL_SIZE = 10  # FIXME: Use this

if COLLECTIVE_FORCE_BINOMIAL_TREE:
    # Disable the flat tree settings.
    FLAT_TREE_MIN = 100
    FLAT_TREE_MAX = 0
    
    # DISABLE HERE AS WELL
    STATIC_FANOUT_MIN = 100
    STATIC_FANOUT_MAX = 0
    
    # Globally enable the binomial tree
    BINOMIAL_TREE_MIN = 0
    BINOMIAL_TREE_MAX = sys.maxint
else:
    FLAT_TREE_MIN = 0
    FLAT_TREE_MAX = 10
    
    # Globally enable the binomial tree
    BINOMIAL_TREE_MIN = 10
    BINOMIAL_TREE_MAX = 50

    STATIC_FANOUT_MIN = 50
    STATIC_FANOUT_MAX = 100

def restrict_tree_changes(name):
    return name.find("TREE") == -1

standard_callbacks = [restrict_tree_changes]